apiVersion: apps/v1
kind: Deployment
metadata:
  name: gologger-deployment
  labels:
    app: gologger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gologger
  template:
    metadata:
      labels:
        app: gologger
    spec:
      containers:
      - name: gologger
        image: ghcr.io/tostaza/gologger:0.0.2
        ports:
        - containerPort: 8080
